;;;; sdl2-image.import.scm - GENERATED BY CHICKEN 4.8.0.5 -*- Scheme -*-

(eval '(import
         (except scheme load)
         chicken
         foreign
         lolevel
         (only sdl2-internals
               define-function-binding
               struct-null?
               %allocate-Uint8
               sdl-failure
               surface?
               unwrap-surface
               wrap-surface
               unwrap-rwops
               wrap-rwops)
         (only sdl2 free-surface! rw-close!)))
(##sys#register-compiled-module
  'sdl2-image
  (list)
  '((init! . sdl2-image#init!)
    (quit! . sdl2-image#quit!)
    (current-version . sdl2-image#current-version)
    (compiled-version . sdl2-image#compiled-version)
    (load . sdl2-image#load)
    (load* . sdl2-image#load*)
    (load-rw . sdl2-image#load-rw)
    (load-rw* . sdl2-image#load-rw*)
    (load-typed-rw . sdl2-image#load-typed-rw)
    (load-typed-rw* . sdl2-image#load-typed-rw*))
  (list)
  (list))

;; END OF FILE
